#!/bin/bash

if [ ! -f compile.sh ]
then
	echo Cannot find my other executables
	exit 1
fi

if [ "$(id -u)" -ne 0 ]
then
	echo Needs to be run as root
	exit 1
fi

if ( which multimon-ng >/dev/null 2>&1 )
then
	multimonbin=multimon-ng
	echo Note: using multimon-ng instead of multimon
else
	multimonbin=multimon
fi

function alert()
{
	echo -e "\033[31m${1}\033[0m" 1>&2
}

# Tempfiles
temp=/tmp/blueballoon_$$
rawfifo=${temp}/raw.fifo
multimonfifo=${temp}/multimon.fifo

function cleanup()
{
	alert "Manager cleaning up"
	pkill -P $$
	# sleep to ensure all the processes are killed before the temp files get killed, prevents segfaults
	sleep 0.5
	rm $temp -r
}
trap cleanup EXIT


# ====  Main ====
alert "Manager started at $temp"

#Start the 'Active High' DTMF pin
./setPin.py 13 1
alert "PIN 13 HIGH"

#Set the 'Ready to recieve' pin
./setPin.py 16 1
alert "PIN 16 HIGH"

mkdir $temp
mkfifo $rawfifo
mkfifo $multimonfifo

rtl_fm -M fm -f 436e6 -s 260k -r 22050 -g 50 $rawfifo &
$multimonbin -a DTMF -t raw $rawfifo > $multimonfifo &

./multimon_processing < $multimonfifo | ./signal_detect
wait
