#!/bin/bash

if [ ! -f compile.sh ]
then
	echo Cannot find my other executables
	exit 1
fi

if [ "$(id -u)" -ne 0 ]
then
	echo Needs to be run as root
	exit 1
fi

if ( which multimon-ng >/dev/null 2>&1 )
then
	multimonbin=multimon-ng
	echo Note: using multimon-ng instead of multimon
else
	multimonbin=multimon
fi

function alert()
{
	echo -e "\033[31m${1}\033[0m" 1>&2
}

# Tempfiles
temp=/tmp/blueballoon_$$
rawfifo=${temp}/raw.raw
multimonfifo=${temp}/multimon.fifo
afifo=${temp}/a.raw
anotherfifo=${temp}/b.raw
loadsafifo=${temp}/c.wav



function cleanup()
{
	alert "Manager cleaning up"
	pkill -P $$
	rm $temp -r
}
trap cleanup EXIT 


# ====  Main ====
alert "Manager started at $temp"

#Start the 'Active High' DTMF pin
./setPin.py 13 1
#Set the 'Ready to recieve' pin
./setPin.py 16 1

mkdir $temp
mkfifo $rawfifo
mkfifo $multimonfifo
mkfifo $afifo
mkfifo $anotherfifo

rtl_fm -M fm -f 436e6 -s 260k -r 22050 -g 50 $afifo &
#sox -r 22050 -e signed-integer -b 16 -v 3.0 $afifo -r 22050 -e signed-integer -b 16 $anotherfifo &
tee $anotherfifo < $afifo | aplay -t raw -f S16_LE -r 22050 &

#| tee >(sox -t raw -r 22050 - soxTest.wav -g 10) \
#  >(aplay -t raw -f S16_LE -r 22050) > cthulu.raw &

$multimonbin -a DTMF -t raw $anotherfifo > $multimonfifo &

./multimon_processing < $multimonfifo | ./signal_detect
wait
