#!bin/sh
# installing shit

echo "Don't leave your seats, you're gonna need to press y a bunch of times"
sleep 5

sudo apt-get update
sudo apt-get install i2c-tools multimon python qt4-dev-tools libusb-1.0 cmake sox gcc
sleep 5

cd /home/pi
mkdir programs
cd programs

git clone https://github.com/steve-m/librtlsdr.git
cd librtlsdr
mkdir build
cd build
cmake ../ -DINSTALL_UDEV_RULES=ON
make
sudo make install
sudo ldconfig

cd /home/pi/programs
git clone https://github.com/EliasOenal/multimon-ng.git
cd multimon-ng
mkdir build
cd build
qmake ../multimon-ng.pro
make
sudo make install

cd /home/pi/programs



# config files
sudo cp /home/pi/RaspberryPiSoftware/newInstallSetup/raspi-blacklist.conf /etc/modprobe.d/raspi-blacklist.conf
sudo cp /home/pi/RaspberryPiSoftware/newInstallSetup/rc.local /etc/rc.local
sudo cp /home/pi/RaspberryPiSoftware/newInstallSetup/modules /etc/modules
